[project]
name = "lavender-report"
version = "0.1.0"
description = "Command-line tool for effortless VAT reporting with Stripe—tailored for EU businesses."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.0",
    "pytz>=2025.2",
    "stripe>=12.1.0",
]
